# tf.where

In [1]:

import tensorflow as tf

tf.where will return the indices of condition that are True, in the form of a 2-D tensor with shape (n, d). (Where n is the number of matching indices in condition, and d is the number of dimensions in condition).

In [2]:
tf.where([True, False, False, True])

<tf.Tensor: shape=(2, 1), dtype=int64, numpy=
array([[0],
       [3]])>

In [5]:
tf.where([[True, False], [False, True]], x=[[1,2],[3,4]] , y=[[5,6],[7,8]] )

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 6],
       [7, 4]], dtype=int32)>

# tf.boolean_mask

In [10]:
import numpy as np
# 2-D example
tensor = [[1, 2], [3, 4], [5, 6]]
mask = np.array([True, False, True])
tf.boolean_mask(tensor, mask)  # [[1, 2], [5, 6]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6]], dtype=int32)>

In [15]:
# 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
t = [1, 2, 1, 3, 1, 1]
#tf.squeeze(t) # [2, 3]
tf.squeeze(t, [2, 4])

InvalidArgumentError: Tried to squeeze dim index 4 for tensor with 1 dimensions. [Op:Squeeze]